local AbstractFile = @record{
  name: string
}

function AbstractFile.open(name: string): AbstractFile
  local file = AbstractFile{name=name}
  print('opened', file.name)
  return file
end

function AbstractFile:__close() -- define __close metamethod
  print('closed', self.name)
end

do
  local file <close> = AbstractFile.open('dummy') -- prints 'opened dummy'
  -- when scope ends, AbstractFile:__close() is called and prints 'closed dummy'
end

